apiVersion: apps/v1
kind: Deployment
metadata:  
  name: echosleephttp
  labels:
    app: echosleephttp
    tier: backend
    version: v1
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: echosleephttp
  template: 
    metadata:
      labels:
        app: echosleephttp
    spec:
      containers:
      - name: echosleephttp
        image: localhost:32000/echosleephttp:latest
        ports:
        - containerPort: 80
